name: HelloWorld
main: myplugin.helloworld.HelloWorld
version: 1.0
api-version: 1.16
commands:
  superkill:
    aliases:
      - "skill"
      - "sk"
      usage: "/superkill <player-name>"
      description: "Kill some player"
      permission: "minecraft.command.kill"
      permission-message: "Only killer can do that!"